import type { Mix, Scenario, SoundId } from "./types";

export const SOUND_LABELS: Record<SoundId, { label: string; emoji: string; category?: string }> = {
  waves: { label: "Onde", emoji: "🌊", category: "Natura" },
  rain: { label: "Pioggia", emoji: "🌧️", category: "Meteo" },
  wind: { label: "Vento", emoji: "🌬️", category: "Meteo" },
  thunder: { label: "Tuoni lontani", emoji: "⚡", category: "Meteo" },
  snow: { label: "Bufera di neve", emoji: "❄️", category: "Meteo" },
  stream: { label: "Ruscello", emoji: "💧", category: "Natura" },
  forest: { label: "Bosco & Uccelli", emoji: "🌲", category: "Natura" },
  night: { label: "Notte estiva", emoji: "🌙", category: "Natura" },
  fire: { label: "Camino a legna", emoji: "🔥", category: "Casa" },
  catPurr: { label: "Fusa del gatto", emoji: "🐱", category: "Casa" },
  hairdryer: { label: "Phon", emoji: "💨", category: "Casa" },
  heater: { label: "Scaldino / Caldobagno", emoji: "♨️", category: "Casa" },
  clock: { label: "Ticchettio orologio", emoji: "🕰️", category: "Casa" },
  train: { label: "Treno", emoji: "🚆", category: "Viaggio" },
  brownNoise: { label: "Rumore bruno", emoji: "🟤", category: "Focus" },
};

export const EMPTY_MIX: Mix = {
  waves: 0,
  rain: 0,
  wind: 0,
  thunder: 0,
  snow: 0,
  stream: 0,
  forest: 0,
  night: 0,
  fire: 0,
  catPurr: 0,
  hairdryer: 0,
  heater: 0,
  clock: 0,
  train: 0,
  brownNoise: 0,
};

export const SCENARIOS: Scenario[] = [
  {
    id: "cabin-snow",
    name: "Baita nella neve",
    emoji: "🪵",
    description: "Camino a legna scoppiettante, vento gelido e bufera di neve fuori dalla finestra.",
    mix: { ...EMPTY_MIX, fire: 68, snow: 55, wind: 30 },
  },
  {
    id: "bathroom-heater",
    name: "Bagno caldo & Relax",
    emoji: "🛁",
    description: "Ronzio avvolgente di scaldino ceramico e getto d'aria calda del phon.",
    mix: { ...EMPTY_MIX, heater: 65, hairdryer: 45 },
  },
  {
    id: "summer-storm",
    name: "Temporale notturno",
    emoji: "⛈️",
    description: "Pioggia battente, raffiche di vento e brontolii maestosi di tuoni in lontananza.",
    mix: { ...EMPTY_MIX, rain: 75, thunder: 70, wind: 32 },
  },
  {
    id: "sea-house",
    name: "Casa sul mare",
    emoji: "🌊",
    description: "Onde lunghe sulla battigia, brezza marina e notte tranquilla.",
    mix: { ...EMPTY_MIX, waves: 75, wind: 22, night: 28 },
  },
  {
    id: "cozy-cat",
    name: "Serata con il gatto",
    emoji: "🐱",
    description: "Fusa profonde e ritmiche sul piumone, camino acceso e pioggia leggera sui vetri.",
    mix: { ...EMPTY_MIX, catPurr: 75, fire: 45, rain: 22 },
  },
  {
    id: "mountain-stream",
    name: "Ruscello alpino",
    emoji: "💧",
    description: "Acqua che gorgoglia fresca tra i sassi, uccellini e brezza tra i pini.",
    mix: { ...EMPTY_MIX, stream: 72, forest: 45, wind: 15 },
  },
  {
    id: "night-train",
    name: "Treno notturno",
    emoji: "🚆",
    description: "Oscillazione regolare sui binari, pioggia leggera e quiete notturna.",
    mix: { ...EMPTY_MIX, train: 72, rain: 24, night: 18 },
  },
  {
    id: "vintage-bedroom",
    name: "Stanza della nonna",
    emoji: "🕰️",
    description: "Il ticchettio rassicurante dell'orologio da parete, il gatto che fa le fusa sulla coperta e il calore del camino.",
    mix: { ...EMPTY_MIX, clock: 65, catPurr: 48, fire: 35, rain: 15 },
  },
  {
    id: "deep-sleep",
    name: "Sonno profondo",
    emoji: "😴",
    description: "Un bozzolo acustico totale: rumore bruno avvolgente, onde lente e pioggia soffusa per bloccare ogni disturbo.",
    mix: { ...EMPTY_MIX, brownNoise: 75, waves: 35, rain: 25 },
  },
];
